apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kura-crm

resources:
  - 01-namespace.yaml
  - 02-configmap.yaml
  - 03-secret.yaml
  - 04-deployment.yaml
  - 05-service.yaml
  - 06-hpa.yaml
  - 07-ingress.yaml
  - 08-network-policy.yaml
  - 09-pdb.yaml
  - 10-mysql.yaml
  - 11-redis.yaml
