apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-deployment.yaml
  - 02-service.yaml
  - 03-hpa.yaml
  - 04-ingress.yaml
  - 05-network-policy.yaml
  - 06-pdb.yaml
images:
  - name: registry.kura-crm.com/kura-crm-web
    newTag: latest
